# Generated by Django 4.2.7 on 2023-12-01 17:24

from django.db import migrations, models
import django.db.models.deletion
import train_maintain.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCrew',
            fields=[
                ('crew_id', models.AutoField(primary_key=True, serialize=False)),
                ('crew_leader', models.CharField(max_length=60)),
                ('specialty_skill', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_model', models.CharField(max_length=15, validators=[train_maintain.models.validate_custom_format])),
                ('max_speed', models.IntegerField()),
                ('no_of_seats', models.IntegerField()),
                ('no_of_toilets', models.IntegerField()),
                ('has_reclining_seats', models.BooleanField()),
                ('has_folding_tables', models.BooleanField()),
                ('has_disability_access', models.BooleanField()),
                ('has_luggage_storage', models.BooleanField()),
                ('has_vending_machine', models.BooleanField()),
                ('has_food_service', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('maintenance_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_maintained', models.DateField()),
                ('condition', models.CharField(max_length=50)),
                ('maintenance_description', models.TextField(max_length=255)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_maintain.maintenancecrew')),
            ],
        ),
    ]
