# Generated by Django 4.2.7 on 2023-12-02 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_maintain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancetask',
            old_name='crew',
            new_name='crew_id',
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='train_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='train_maintain.train'),
            preserve_default=False,
        ),
    ]
