# Generated by Django 4.2.7 on 2023-12-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_maintain', '0002_rename_crew_maintenancetask_crew_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancetask',
            old_name='crew_id',
            new_name='crew',
        ),
        migrations.RenameField(
            model_name='maintenancetask',
            old_name='train_id',
            new_name='train',
        ),
    ]
